### ISSUE TITLE
Cannot load guardians list

### ISSUE THREAD

**Issue by Eddy-orbs** [orbs-network/staking-wallet#114]
![image](https://user-images.githubusercontent.com/56513320/116953625-b381d880-acc8-11eb-9d66-2d69d6acc28b.png)

Since few days ago. It does not look a client's network issue.
please check internal loading mechanisim.

**Comment by Eddy-orbs** [comment]
nodeEndpoints = ['https://0xcore.orbs.com/services/management-service/status'];

I think loading endpoint URL takes too long. (size of response 7 MB+)

**Comment by ronnno** [comment]
Do you have more specific reproduction scenario? what platform/browser? is this confined to one geographical area/network provider? (maybe does not happen/happens more often when using 4G?)

I am unable to  reproduce

**Comment by ronnno** [comment]
I am not sure the size of the file is a problem. This could be caused by issues with nginx, AWS, network, EFS, or the service itself. 

What I mean is that we should monitor download times. I can setup Pingdom to measure two downloads - the status page, and the node management config (which is smaller) and then we can compare download times over a few days, and contrast the measurement with file size.

Also, constantly reading from the status page could possibly prevent this issue in some cases. we can see that also through this experiment

**Comment by ronnno** [comment]
Running metrics for a couple of days show that the files typically download under 10 seconds - and occationally exceed 10 seconds. I have not registered any failure to download (using Pingdom).

The code also should have a retry count of 3. 
A possible issue can be partial or corrupt JSON format.

We should extract the actual retry count, log errors, and report corrupt JSON format to detect the source of the issue. 

Additionally, we can review the retry mechanism - see if it would use cached data in case of corrupt JSON

**Comment by ronnno** [comment]
Alerts now show connection timeout in some cases.
Probably related to load on the node. Need to tune nginx, log errors, monitor performance of nginx (??) and add error logging to Tetra.

In addition, we will move the history part of the committeeEvents array to a separate endpoint so that this page will be reduced to under 50KB - this should reduce the load from the nginx as a workaround

**Comment by Eddy-orbs** [comment]
Fixed. Thanks Ron!
